apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-webhook-server
  labels:
    control-plane: elastic-operator
  {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookServer.type }}
  selector:
    control-plane: elastic-operator
  {{- include "operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookServer.ports | toYaml | nindent 2 -}}