apiVersion: v1
      #  storageClassName: local-storage
kind: PersistentVolumeClaim

metadata:
  name: postgres-pv-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2500Mi
  #storageClassName: yourClass
