apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filter-service.fullname" . }}
  labels:
    {{- include "filter-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "filter-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filter-service.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: dockersecret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: docker.io/dockercgs/filter-service:latest
          imagePullPolicy: Always 
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      
  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "FLINK_CLUSTER_HOST"
              value: {{ .Values.flinkCluster.host }}
            - name: "FLINK_CLUSTER_PORT"
              value: {{ .Values.flinkCluster.port | quote }}
            - name: "KAFKA_BROKERS"
              value: {{ .Values.kafka.brokers }}
            - name: "SCHEMA_REGISTRY_ADDRESS"
              value: {{ .Values.kafka.schemaRegistry }}
            - name: "REDIS_HOST"
              value: {{ .Values.redis.host }}
            - name: "REDIS_PORT"
              value: {{ .Values.redis.port | quote }}
            - name: "REDIS_PASSWORD"
              value: {{ .Values.redis.pass }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
