apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-prod1.fullname" . }}-config
  labels:
  {{- include "postgres-prod1.labels" . | nindent 4 }}
data:
  POSTGRES_DRIVER: {{ .Values.config.postgresDriver | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.postgresPort | quote }}