apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres-prod1.fullname" . }}-pv-claim
  labels:
    app: postgres
  {{- include "postgres-prod1.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.pvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.pvClaim.storageClass | quote }}
  volumeName: postgres-pv-volume