apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres-prod1.fullname" . }}-pv-volume
  labels:
    app: postgres
    type: local
  {{- include "postgres-prod1.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/postgres
  storageClassName: local-storage