apiVersion: v1
kind: Service
metadata:
  name: filterservice
  labels:
  {{- include "webapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.filterservice.type }}
  selector:
    app: filterservice
  {{- include "webapp-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.filterservice.ports | toYaml | nindent 2 -}}
