apiVersion: v1
kind: Service
metadata:
  name: livetail
  labels:
  {{- include "webapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.livetail.type }}
  selector:
    app: livetail
  {{- include "webapp-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.livetail.ports | toYaml | nindent 2 -}}
