apiVersion: v1
kind: ConfigMap
metadata:
  name: gowebapi-config
data:
  API_NAME: web-api
  API_HOST: localhost
  API_PORT: "8000"
  API_ENV: development
  API_REQUEST_LOG: "true"
  API_MAILER_SMTP_SERVER: email-smtp.us-east-1.amazonaws.com
  API_MAILER_EMAIL: support@logfire.sh
  Client_BASE_URL: logfire.sh