# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - name: Build
      working-directory: gowebapp/web-api
      run: go build -v ./...

    - name: Test
      working-directory: gowebapp/web-api
      run: go test -v ./...

    - name: Build and Push Docker logfire/gowebapi:latest
      uses: docker/build-push-action@v2
      with:
        context: gowebapp/web-api
        push: true
        tags: dockercgs/goweb-api:latest
        registry: docker.io
      env:
        DOCKER_USERNAME: dockercgs
        DOCKER_PASSWORD: Mohamed@1234
